/**
 * HostManager: dsh web host lifecycle (discovery, spawn, version check).
 * Contract: ARCHITECTURE.md section 4.2. Loopback only (127.0.0.1); the
 * vscode import is type-only so this module stays unit-testable under plain
 * Node (node:test), never loading the `vscode` runtime module.
 */

import { spawn as spawnChild, type ChildProcess } from 'node:child_process'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import * as crypto from 'node:crypto'
import type * as vscode from 'vscode'
import type { ClientRequest, ServerResponse } from './protocol/rpc'
import { RpcId } from './protocol/rpc'
import type { HostDescription } from './protocol/host'

const execFileAsync = promisify(execFile)

/** Read the browser-session cookie generated by dsh from .credentials.yaml. */
export function getLocalDshCookie(authority: string): string | null {
  try {
    const credPath = path.join(os.homedir(), '.dsh', '.credentials.yaml')
    if (!fs.existsSync(credPath)) return null
    const content = fs.readFileSync(credPath, 'utf8')
    const match = /client-connection\/browser-session:[\s\S]*?secret:\s*([A-Za-z0-9_-]+)/.exec(content)
    if (!match || !match[1]) return null
    const secretStr = match[1]
    const padding = '='.repeat((4 - secretStr.length % 4) % 4)
    const secret = Buffer.from(secretStr.replaceAll('-', '+').replaceAll('_', '/') + padding, 'base64')
    const cookieName = 'dsh-auth-' + Buffer.from(crypto.createHash('sha256').update(authority).digest()).toString('base64').replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/, '')
    const now = Date.now()
    const payload = {
      version: 1,
      authority,
      issuedAt: now,
      expiresAt: now + 30 * 24 * 3600 * 1000,
    }
    const body = Buffer.from(JSON.stringify(payload), 'utf8').toString('base64').replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/, '')
    const sig = Buffer.from(crypto.createHmac('sha256', secret).update(body).digest()).toString('base64').replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/, '')
    return `${cookieName}=v1.${body}.${sig}`
  } catch {
    return null
  }
}

/** Connection facts about a reachable (or freshly spawned) dsh host. */
export interface HostInfo {
  port: number
  pid?: number
  spawnedByUs: boolean
  token?: string
  cookie?: string
}

/** dsh package used when no `dsh` binary is on PATH. */
const DSH_PACKAGE = '@deepseek-ai/dsh@0.1.0-rc.6'
/**
 * Compatible host version prefixes (mirrors package.json `dsh.compatibleVersionPrefixes`).
 * Note: the published 0.1.0-rc.6 npm package reports app version "0.0.1" from
 * host.describe, while a dev/PATH dsh reports its real "0.1.*" version.
 */
const COMPATIBLE_VERSION_PREFIXES = ['0.1.', '0.0.1']
/** Health-check RPC (the only probe endpoint; never invent others). */
const PROBE_METHOD = 'host.describe'
/** Ports scanned in order starting from basePort. */
const PORT_SCAN_LIMIT = 10
/** Per-probe HTTP deadline; a hung listener must not stall startup. */
const PROBE_TIMEOUT_MS = 1500
/** Spawn readiness deadline (first `npx` run downloads the package; measured ~4.5min cold). */
const SPAWN_READY_TIMEOUT_MS = 600_000
/** Poll interval while waiting for a spawned host to answer. */
const SPAWN_POLL_MS = 500

/** Minimal logger shape so tests can substitute a plain object. */
type Logger = Pick<vscode.OutputChannel, 'appendLine'>

/** POSIX-ish names accepted as environment variable keys (Windows also allow `=`). */
const ENV_KEY_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/

/**
 * Clean a user-supplied environment variable map (the `dsh.env` setting) into
 * something safe to hand to `spawn`: trimmed keys, non-empty values, and only
 * syntactically valid names. Dropped entries are counted so the caller can warn
 * instead of silently ignoring a typo.
 * @param raw - the configured object (untrusted, may hold non-strings).
 * @returns the cleaned map plus how many entries were dropped.
 */
export function normalizeEnv(raw: Record<string, unknown> | undefined): { env: Record<string, string>; dropped: number } {
  const env: Record<string, string> = {}
  let dropped = 0
  for (const [key, value] of Object.entries(raw ?? {})) {
    const name = key.trim()
    // Values are passed verbatim (a secret may legitimately hold spaces); an
    // empty string is dropped because it would shadow an inherited variable.
    if (!ENV_KEY_PATTERN.test(name) || typeof value !== 'string' || value === '') {
      dropped++
      continue
    }
    env[name] = value
  }
  return { env, dropped }
}

/**
 * Owns the dsh host process lifecycle: probe candidate ports for an existing
 * host, spawn one when absent, verify version compatibility, kill on dispose.
 */
export class HostManager {
  /** First port to probe (set from the `dsh.port` configuration; tests override). */
  basePort = 3080
  /**
   * Custom environment variables injected into a spawned host (set from the
   * `dsh.env` configuration; tests override). Only the process this manager
   * spawns sees them — an already-running host keeps its own environment.
   */
  customEnv: Record<string, string> = {}
  /** Token configured for external dsh hosts requiring auth. */
  token?: string
  private child: ChildProcess | null = null

  constructor(private readonly log: Logger) {}

  /**
   * Ensure a host is available: probe basePort..basePort+9 in order and use the
   * first live one; when none answers, spawn on the first port that is free.
   * @returns connection info of the selected host.
   */
  async ensureHost(): Promise<HostInfo> {
    for (let port = this.basePort; port < this.basePort + PORT_SCAN_LIMIT; port++) {
      if (await this.probe(port, this.token)) {
        this.log.appendLine(`[host-manager] found existing dsh host on 127.0.0.1:${port}`)
        const cookie = getLocalDshCookie(`127.0.0.1:${port}`) ?? undefined
        return { port, spawnedByUs: false, token: this.token, cookie }
      }
    }
    const port = await this.firstFreePort()
    this.log.appendLine(`[host-manager] no live host; spawning on 127.0.0.1:${port}`)
    return this.spawn(port)
  }

  /**
   * Probe one port for a dsh host: POST /api/host.describe or /api/settings/describe and accept only a
   * well-formed ok ServerResponse.
   * @param port - loopback port to probe.
   * @param token - optional Bearer auth token.
   * @returns true when a dsh host answered the health check.
   */
  async probe(port: number, token?: string): Promise<boolean> {
    const authority = `127.0.0.1:${port}`
    const cookie = getLocalDshCookie(authority)
    const probeEndpoints = [
      { method: PROBE_METHOD, payload: {} },
      { method: 'settings/describe', payload: { args: {} } },
    ]

    for (const ep of probeEndpoints) {
      try {
        const request: ClientRequest = {
          type: 'client-request',
          rpcId: RpcId(crypto.randomUUID()),
          method: ep.method,
          payload: ep.payload,
        }
        const headers: Record<string, string> = { 'content-type': 'application/json' }
        if (token) {
          headers['Authorization'] = `Bearer ${token}`
        }
        if (cookie) {
          headers['Cookie'] = cookie
        }
        const response = await fetch(`http://127.0.0.1:${port}/api/${ep.method}`, {
          method: 'POST',
          headers,
          body: JSON.stringify(request),
          signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
        })
        if (!response.ok) continue
        const body = (await response.json()) as ServerResponse
        if (body.type === 'server-response' && body.rpcId === request.rpcId && body.result.ok) {
          return true
        }
      } catch {
        // try next probe endpoint
      }
    }
    return false
  }

  /**
   * Spawn `dsh web --host 127.0.0.1 --port <port>` (PATH binary preferred,
   * `npx -y <package>` fallback) and poll the probe until it answers.
   * `customEnv` rides the child environment (merged over process.env).
   * @param port - port the host must listen on.
   * @returns connection info including the child pid.
   */
  async spawn(port: number): Promise<HostInfo> {
    const command = await this.resolveCommand()
    // Generate a random token for this spawned session if not explicitly provided
    const spawnedToken = this.token ?? crypto.randomUUID()
    // --no-open（AGENTS.md）: the sidebar itself is the UI — spawning the host
    // must not pop the dsh Web UI in the default browser (e2e included).
    const args = [...command.args, 'web', '--no-open', '--host', '127.0.0.1', '--port', String(port)]
    this.log.appendLine(`[host-manager] spawn: ${command.bin} ${args.join(' ')}`)
    // Custom env keys are logged by NAME only: the values are typically secrets.
    const envKeys = Object.keys(this.customEnv)
    if (envKeys.length > 0) this.log.appendLine(`[host-manager] custom env: ${envKeys.join(', ')}`)

    let detectedToken: string | null = null
    const tokenRegex = /(?:token[=:\s]+|Authorization:\s+Bearer\s+)([A-Za-z0-9_-]+)/i

    // detached (POSIX): the npx fallback is a wrapper chain (npx -> sh -> node);
    // its own process group lets dispose() kill the whole tree instead of
    // orphaning the real host process.
    // On Windows, running batch files (.cmd/.bat) requires shell: true.
    const child = spawnChild(command.bin, args, {
      stdio: ['ignore', 'pipe', 'pipe'],
      detached: process.platform !== 'win32',
      shell: process.platform === 'win32',
      cwd: process.platform === 'win32' ? os.homedir() : undefined,
      // Explicit merge: posix-spawn REPLACES the environment when `env` is
      // given, so a bare customEnv would drop PATH and everything else.
      env: { ...process.env, DSH_AUTH_TOKEN: spawnedToken, ...this.customEnv },
    })
    this.child = child
    child.stdout?.on('data', (chunk: Buffer) => {
      const text = chunk.toString()
      const match = tokenRegex.exec(text)
      if (match && match[1]) {
        detectedToken = match[1]
      }
      this.log.appendLine(`[dsh] ${text.trimEnd()}`)
    })
    child.stderr?.on('data', (chunk: Buffer) => this.log.appendLine(`[dsh:err] ${chunk.toString().trimEnd()}`))
    child.on('exit', (code) => {
      this.log.appendLine(`[host-manager] dsh host exited with code ${String(code)}`)
      if (this.child === child) this.child = null
    })

    const effectiveToken = () => detectedToken ?? spawnedToken
    const deadline = Date.now() + SPAWN_READY_TIMEOUT_MS
    while (Date.now() < deadline) {
      if (child.exitCode !== null) throw new Error(`dsh host exited during startup (code ${String(child.exitCode)})`)
      if (await this.probe(port, effectiveToken())) {
        const cookie = getLocalDshCookie(`127.0.0.1:${port}`) ?? undefined
        return { port, pid: child.pid, spawnedByUs: true, token: effectiveToken(), cookie }
      }
      if (await this.probe(port)) {
        const cookie = getLocalDshCookie(`127.0.0.1:${port}`) ?? undefined
        return { port, pid: child.pid, spawnedByUs: true, cookie }
      }
      await new Promise((resolve) => setTimeout(resolve, SPAWN_POLL_MS))
    }
    child.kill()
    throw new Error(`dsh host did not become ready on port ${port} within ${SPAWN_READY_TIMEOUT_MS}ms`)
  }

  /**
   * Read the host version via host.describe and compare it with the plugin's
   * declared compatible prefixes (COMPATIBLE_VERSION_PREFIXES).
   * @param info - the host to interrogate.
   * @returns a warning message when the version matches no prefix, else null.
   */
  async checkVersion(info: HostInfo): Promise<string | null> {
    const request: ClientRequest = {
      type: 'client-request',
      rpcId: RpcId(crypto.randomUUID()),
      method: PROBE_METHOD,
      payload: {},
    }
    const headers: Record<string, string> = { 'content-type': 'application/json' }
    if (info.token) {
      headers['Authorization'] = `Bearer ${info.token}`
    }
    if (info.cookie) {
      headers['Cookie'] = info.cookie
    }
    const response = await fetch(`http://127.0.0.1:${info.port}/api/${PROBE_METHOD}`, {
      method: 'POST',
      headers,
      body: JSON.stringify(request),
      signal: AbortSignal.timeout(5000),
    })
    if (!response.ok) {
      // If host.describe doesn't exist (e.g., 0.1.5+ with Typert gateway), verify with settings/describe
      const altResponse = await fetch(`http://127.0.0.1:${info.port}/api/settings/describe`, {
        method: 'POST',
        headers,
        body: JSON.stringify({ type: 'client-request', rpcId: request.rpcId, method: 'settings/describe', payload: { args: {} } }),
        signal: AbortSignal.timeout(5000),
      })
      if (altResponse.ok) return null
      return `无法读取 dsh 版本（HTTP ${response.status}），请确认 dsh 已正常启动`
    }
    const body = (await response.json()) as ServerResponse
    if (!body.result.ok) return `host.describe 失败：${body.result.error.message}`
    const description = body.result.value as HostDescription
    if (!COMPATIBLE_VERSION_PREFIXES.some((prefix) => description.version.startsWith(prefix))) {
      return `dsh 版本 ${description.version} 与插件兼容范围 ${COMPATIBLE_VERSION_PREFIXES.join(' / ')}* 不匹配，请升级 dsh`
    }
    return null
  }

  /** Kill the child process when (and only when) this manager spawned it. */
  async dispose(): Promise<void> {
    const child = this.child
    this.child = null
    if (child && child.exitCode === null) {
      this.log.appendLine('[host-manager] killing spawned dsh host')
      // Kill the whole POSIX process group (see the detached spawn): a plain
      // kill only reaches the npx wrapper and leaks the real host.
      if (process.platform !== 'win32' && child.pid !== undefined) {
        try {
          process.kill(-child.pid, 'SIGTERM')
          return
        } catch {
          // Group already gone — fall through to the direct kill.
        }
      }
      child.kill()
    }
  }

  /** First port in the scan range with nothing listening (probe already failed there). */
  private async firstFreePort(): Promise<number> {
    const net = await import('node:net')
    for (let port = this.basePort; port < this.basePort + PORT_SCAN_LIMIT; port++) {
      const free = await new Promise<boolean>((resolve) => {
        const server = net.createServer()
        server.once('error', () => resolve(false))
        server.once('listening', () => server.close(() => resolve(true)))
        server.listen(port, '127.0.0.1')
      })
      if (free) return port
    }
    throw new Error(`no free port in ${this.basePort}..${this.basePort + PORT_SCAN_LIMIT - 1}`)
  }

  /** Resolve the spawn command: `dsh` on PATH wins, else the pinned npx package. */
  private async resolveCommand(): Promise<{ bin: string; args: string[] }> {
    try {
      const checker = process.platform === 'win32' ? 'where.exe' : 'which'
      await execFileAsync(checker, ['dsh'])
      const bin = process.platform === 'win32' ? 'dsh.cmd' : 'dsh'
      return { bin, args: [] }
    } catch {
      const npxCmd = process.platform === 'win32' ? 'npx.cmd' : 'npx'
      return { bin: npxCmd, args: ['-y', DSH_PACKAGE] }
    }
  }
}
